site_name: Kubedim
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Troubleshooting: troubleshooting.md
  - Advanced Usage: advanced.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
